### PR TITLE
Support installation of multiple files

### PR DESCRIPTION
**Pull request by harens**
Following from the [stackoverflow question](https://stackoverflow.com/questions/71172307/brew-formula-install-with-multiple-files), I've modified the `install` function to install all the files present, and then to create a symlink to the `angler` file.

I'll explain in more detail why these changes work in the original question.

Additional changes made:
- Add upstream source option via HEAD
- Bump to python@3.10

### CODE REVIEW

**Review by Deitsch — COMMENTED** [review]
First and foremost, big thanks, it looks promising! Just some follow up questions before merging it: 
What does revision and head mean in a Formula file?
How did you come up with that? `packages = libexec/"lib/python#{xy}/site-packages/angler"` Where did you "find" this path to copy the files to??

**Comment by harens** [comment]
> What does revision and head mean in a Formula file?

#### revision

There might be some users who have already downloaded angler via homebrew. Adding a revision indicates that their version of angler 0.0.2 is outdated and needs to be rebuilt. ([docs link](https://docs.brew.sh/Formula-Cookbook#formulae-revisions))

#### head

Some users might like to live on the bleeding edge. `--HEAD` allows them to build the latest commit. ([docs link](https://docs.brew.sh/Formula-Cookbook#unstable-versions-head))

```
$ brew install --HEAD angler
```
I'm more than happy to answer any more questions you might have. Thanks for reviewing @Deitsch.

**Comment by Deitsch** [comment]
Ah i see, makes sense thanks! I updated my initial question while you were answering i think, did you see those?

**Comment by harens** [comment]
>  I updated my initial question while you were answering i think, did you see those?

No I didn't ;) Thanks for pointing it out.

> How did you come up with that? packages = libexec/"lib/python#{xy}/site-packages/angler" Where did you find this path to copy the files to??

This is just the standard location for python modules. Therefore, I just put all the files in its own angler directory. ([docs link](https://docs.brew.sh/Homebrew-and-Python#site-packages-and-the-pythonpath))

One thing I didn't account for is whether the user ever wants to import angler as a library. I didn't account for this since it seems to be just a command line tool, but it should (hopefully) be easy to get up and working if that's something you want.

**Comment by Deitsch** [comment]
Ah, i see. I expected that the files would be moved into the brew cellar in the same dir as angler itself. So basically python just check its default folder for the files which just got moved there and it works - right? (i'm new to python, thanks for explaining! - coming from swift & angular)

Yes it's just a command line tool, so it should be fine!

**Comment by harens** [comment]
> Ah, i see. I expected that the files would be moved into the brew cellar in the same dir as angler itself.

The end result is that everything is in the same brew cellar. I just put in the standard subdirectories within the cellar.

```
$ brew list angler
/usr/local/Cellar/angler/0.0.2_1/bin/angler
/usr/local/Cellar/angler/0.0.2_1/lib/python3.10/site-packages/homebrew-angler.pth
/usr/local/Cellar/angler/0.0.2_1/libexec/lib/ (7 files)
```

> So basically python just check its default folder for the files which just got moved there and it works - right? 

I could've put it anywhere to be fair, as long as all the python files are together. It doesn't matter since I symlink the `angler` binary to `/usr/local/bin` no matter where it is.

The only reason I put it in `site-packages` is since that's the standard location for python modules.

> Yes it's just a command line tool, so it should be fine!

So...I thought that since we're here, I might as well try to write the best homebrew formula I can. This was actually a lot trickier than expected since the project structure is a bit unusual. I had to modify the python path so all the imports worked, but now it's all good! You can find out more [here](https://docs.brew.sh/Python-for-Formula-Authors#installing-1) and [here](https://docs.python.org/3/library/sys.html#sys.path), and please feel free to ask me questions if you have any.

```python
$ /usr/local/bin/python3.10
Python 3.10.2 (main, Feb  2 2022, 08:42:42) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from angler.anglerHelperFunctions import readFromJson
>>>
```

**Comment by harens** [comment]
I thought I'd add some basic tests whilst we're here too. And with that, we're done! 🎉

**Comment by Deitsch** [comment]
I think i'm slowly getting it. My initial miss understanding was that the current working directory is the cellar. You are creating the folders in there and move stuff. 

I don't understand what this is needed for
```ruby
# Allow imports from CLT and as a library
(angler_package/"__init__.py").write <<~EOS
    import sys
    sys.path.append("#{angler_package}")
EOS
```

What's the issue there. I am open to any suggestion. This is my first time writing a python tool and python in general. 
> project structure is a bit unusual

Thanks for helping me a ton! We can move this to Discord or whatever if you want cause this already goes way beyond a MR 🚀

**Comment by harens** [comment]
> I don't understand what this is needed for...

It's all to do with the whacky world of relative imports in python, or more specifically, this line in [`anglerHelperFunctions.py`](https://github.com/Deitsch/angler/blob/main/anglerHelperFunctions.py):

```python
from anglerEnums import AnglerConfig
```
This line is basically saying, look in the current directory of where python is being run for `angularEnums`. This works fine when you run python from within the `angular` directory. However, if I was in a different directory, python wouldn't be able to find the file.

```
$ /usr/local/bin/python3.10
Python 3.10.2 (main, Feb  2 2022, 08:42:42) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from angler.anglerHelperFunctions import __extractPath
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/angler/0.0.2_1/libexec/lib/python3.10/site-packages/angler/anglerHelperFunctions.py", line 2, in <module>
    from anglerEnums import AnglerConfig
ModuleNotFoundError: No module named 'anglerEnums
```

However, it's important to note that python does know where the angler package is. That's because of the pth file, which basically points python to look in the homebrew cellar.

```
> /usr/local/bin/python3.10
Python 3.10.2 (main, Feb  2 2022, 08:42:42) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import angler
>>>
```

So, to get around this import issue, I basically said the following. If angler is currently being imported, look for the other angler files (e.g. AnglerEnums) in the homebrew cellar.

How did I do this? There's a special file called `__init__.py` which, if it exists, is run whenever angler is imported. Within the homebrew formula, I created this file with the following contents:

*Whenever angler is imported, modify the path python searches in so that it can find the modules.*

All of this logic for those four lines of code ;) But it does the job. My explanation can almost certainly be improved, so please ask if something's not clear.

> This is my first time writing a python tool and python in general.

You've done an amazing job, certainly much better than if I tried writing swift. 😄 As you mention, the project structure is certainly out of scope for this PR, but I'd still love to help. Feel free to ping Haren#9624.

**Pull request merged**
